### ISSUE TITLE
online SDK documentation has broken links

### ISSUE THREAD

**Issue by corybarr** [landing-ai/landingai-python#133]
To reproduce:

- head to https://landing-ai.github.io/landingai-python/landingai.html
- Click on the Webcam (or other) link
- 404 Page Not Found error

**Comment by pappacena** [comment]
Hi, @corybarr !

We are migrating our docs tool, and the new URL for that should be https://landing-ai.github.io/landingai-python/ .

Would you mind sharing where did you click to arrive at the old link? We might need to update it.

**Comment by corybarr** [comment]
Unfortunately, I don't recall. It might have been via web search, but nearly equally as probably via a link. I'm not positive and can't reproduce.
